### ISSUE TITLE
Can't create the Mesh at Blender 3.1

### ISSUE THREAD

**Issue by sigillumrensil** [serzh272/GearGenMaster#6]
First of all I am not a good english speaker but I will try.

I have used this addon at Blender 3.0.0 and it works realy fine, awesome work by the way, I love the addon.
The issue started when I migrate to Blender 3.1.0.
It gives me this mensage when I click to create a new mesh.

```
Error: Python: Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\GearGenMaster-0_1_7\GearGenMaster.py", line 381, in invoke
    self.execute(context)
  File "C:\Users\<user>\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\GearGenMaster-0_1_7\GearGenMaster.py", line 290, in execute
    mesh = addMesh.createMesh(self, context)
  File "C:\Users\<user>\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\GearGenMaster-0_1_7\addMesh.py", line 1266, in createMesh
    mesh = createGearMesh(m=pr.ggm_module,
  File "C:\Users\<user>\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\GearGenMaster-0_1_7\addMesh.py", line 1239, in createGearMesh
    mesh.from_pydata(VEF[0], VEF[1], VEF[2])
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\bpy_types.py", line 531, in from_pydata
    self.polygons.foreach_set("vertices", vertex_indices)
TypeError: couldn't access the py sequence

location: <unknown location>:-1
```

**Comment by macnavi** [comment]
You are not the only one experiencing this issue. It doesn't work neither in 3.2.0. It seems not compatible with the later versions. As this is a much better gear generator than the add-on that is delivered with Blender, as the gear changes its diameter by setting the module size and not radius, I hope this add-on will be updated and supporting the later Blender versions.
For the time being, you'll have to use Blender 2.93 with this add-on to create your gear.

**Comment by yar3333** [comment]
I made a pull request to support Blender 3.1. For a while, you can look at forked repo: https://github.com/yar3333/GearGenMaster

**Comment by Testingblender** [comment]
> I made a pull request to support Blender 3.1. For a while, you can look at forked repo: https://github.com/yar3333/GearGenMaster

Not working

**Comment by tommyinb** [comment]
> I made a pull request to support Blender 3.1. For a while, you can look at forked repo: https://github.com/yar3333/GearGenMaster

Your version works! Thank you

**Comment by csmgj** [comment]
I'm using Blender 3.0.1 on Linux Mint. I removed the old GearGenMaster zip and installed the new one from 
https://github.com/yar3333/GearGenMaster
It does not work. So I upgraded to 3.6.4 and it works fine. Thanks.

**Comment by schmidhguen** [comment]
I looked it up today and solved the issue. It’s now useable in blender 4.2 and normally also before. The problem is that in the array of the faces, the needed integer values are written as float values …  i will later upload my file

**Comment by Mikit3d** [comment]
> I looked it up today and solved the issue. It’s now useable in blender 4.2 and normally also before. The problem is that in the array of the faces, the needed integer values are written as float values … i will later upload my file

Please we are in need of the new code for this amazing addon...
Thank you
